### PR TITLE
Limit and offset on portals

### PR DESCRIPTION
**Pull request by woller**
Hi beezwax

I've added the ability use the limit and offset params on portals

### CODE REVIEW

**Comment by pilaf** [comment]
@woller Thanks again!

Unfortunately I will not be merging this one as I'd like to put some extra thought on the API design here. This feature has been long missing though, so I'll give it high priority and work on it next.

**Comment by woller** [comment]
@pilaf Understandable that you want a clean api. We just ended up putting it in the limit-method, as it seemed like an easy place to make it work, though the portal/includes method might be better. 
Do you happen to have a road map for the project? We have a bunch of projects coming up that would benefit from this gem and we would be happy to help, where we can 😃

**Comment by pilaf** [comment]
@woller I had misinterpreted how your change worked. Apologies.

I will review it soon and most likely merge it with some light modifications.

As for a roadmap, look for open issues labeled as "enhancement" and assigned the 0.9 milestone:

https://github.com/beezwax/fmrest-ruby/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.9

0.9 (not necessarily the actual version number) is meant to be the point where we have 100% (or close to 100%) coverage of the DAPI specs.

And thanks again for your contributions!

**Comment by woller** [comment]
@pilaf That sounds great :) How much do you want to emulate ActiveRecord? I was considering adding first and last class methods to the model, as it is something I use often for debugging and I'm getting tired of writing `SomeClass.limit(1).first`

**Comment by pilaf** [comment]
@woller I'm up for that, although I'm not sure `last` could be properly implemented with the DAPI (it could probably work by inverting the sorting when one exists, but that's not possible if no sorting was provided I think).

There's also currently a `find_one` (provided by Spyke) which works somewhat like `first`, but I'm not sure if it's provided at the class level or only on scopes. If you implement `first` consider making it an alias of `find_one` (unless there's a real functionality difference I'm not seeing) and making sure both methods are available at class level too.

**Comment by pilaf** [comment]
@woller I did a rebase and added some modifications to your PR, but it's now merged and released (v0.4.0).

**Pull request closed without merging**
