### PR TITLE
Support Rails / ActiveRecord 7.1

### LINKED ISSUE #48: Broken on Rails 7.1
I'm running into a few errors after upgrading to Rails 7.1:

```
NoMethodError: undefined method `attribute_method_matchers' for FmRest::Spyke::Base:Class

          self.attribute_method_matchers.shift
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
Did you mean?  attribute_method_patterns
               attribute_method_patterns?
               attribute_method_patterns=
               attribute_method_affix
from lib/ruby/gems/3.1.0/gems/fmrest-spyke-0.24.0/lib/fmrest/spyke/model/attributes.rb:25:in `block in <module:Attributes>'
```

`attribute_method_matchers` was changed to `attribute_method_patterns` [here](https://github.com/rails/rails/pull/44367/files)

```
NameError: undefined local variable or method `mapped_attributes' for Filemaker::Events:Class

            self.mapped_attributes = mapped_attributes.merge(from => to.to_s).freeze
                                     ^^^^^^^^^^^^^^^^^
from lib/ruby/gems/3.1.0/gems/fmrest-spyke-0.24.0/lib/fmrest/spyke/model/attributes.rb:107:in `_fmrest_define_attribute'
```
as well as a `TypeError: superclass mismatch for class Foo` in my classes that subclass `FmRest::Layout('whatever')`

I haven't had a chance to look into these other two issues yet...

### PR DESCRIPTION
**Pull request by emptyflask**
resolves #48 

this has been rebased onto #50, so you might want to merge that first if you want more isolated squashed commits

### CODE REVIEW

**Comment by emptyflask** [comment]
@pilaf I'm using my own fork for now but it would be great if you could merge this before the holidays!

**Comment by pilaf** [comment]
@emptyflask Thanks a lot for the PR and sorry for the late response. I'll prepare a new version release in a bit.

**Comment by pilaf** [comment]
@emptyflask I've just released fmrest 0.26.0-rc1. If you could install it and confirm that it's working properly for you I'll release the final 0.26.0.

**Comment by emptyflask** [comment]
@pilaf Tested under Rails 7.0 and 7.1, looks good to me!

**Comment by pilaf** [comment]
@emptyflask 0.26.0 released 🚀 

Thanks again for the PR and the help.

**Pull request merged**
